pJS <- phantom()
web <- remoteDriver(browserName = 'phantomjs')
web$open()
web$navigate(url = "http://www.profootballfocus.com/amember/login")
nameBox <- web$findElement("name","amember_login")
pwBox <- web$findElement("name","amember_pass")
nameBox$sendKeysToElement(list("Benjaminryanclarke@icloud.com"))
pwBox$sendKeysToElement(list("tjk589682"))
submitButton <- web$findElement("xpath","/html/body/div[1]/div[2]/div/div[1]/div[1]/div/form/fieldset/div[7]/div/input")
submitButton$clickElement()
web$navigate(url = "http://www.profootballfocus.com/toolkit/wr-cb-chart/")
wrCbChart <- web$findElement("xpath","//*[@id='chart']")
wrCbChartHTML <- wrCbChart$copy()
wrChart <- as.character(wrCbChartHTML$getElementText())
wrCbTable <- readHTMLTable(wrChart)
